bind_addresses:
  # protocol: local socket address
  basic:
    - "0.0.0.0:8900"
    - "[::]:8900"
  tcp: "0.0.0.0:8903"
  quic: "0.0.0.0:8904"

# optional unless using quic
certificates:
  private_key: tests/cert.key
  server_certificate_chain: tests/cert.crt
  # certificates to verify
  remote_certificates: tests/cert-verify

# send_using_address and visible_ip are per group as well
send_using_address: "0.0.0.0:8901"

# if behind nat/incorrect ip is used
visible_ip: "my-public-ip"

# max bytes to receive per connection
max_receive_buffer: 10485760
# max bytes per file when sending/receiving files
max_file_size: 1048576

# whether to send initial clipboard when application starts
send_clipboard_on_startup: false

# if receiving once how many seconds to wait
receive_once_wait: 20

groups:
  specific_hosts:
    key: "32323232323232323232323232323232"
    allowed_hosts:
      - "192.168.0.153:8900"
      - "192.168.0.54:20034"
    clipboard: clipboard # can be clipboard, /path/to/file , /path/to/directory/
  local_network: # allowed_hosts default to local network multicast
    key: "32323232323232323232323232323232"
  nat_traversal_client1:
    key: "32323232323232323232323232323232"
    visible_ip: "2.2.2.2" # if not provided defaults to public ip when sending to external networks
    send_using_address:
      - "0.0.0.0:8900"
      - "[::]:8900"
    heartbeat: 20 # send dummy packet every 20 seconds
    allowed_hosts:
      - "external.net:8900"
  nat_traversal_client2: # on the other host
    key: "32323232323232323232323232323232"
    visible_ip: "external.net"
    send_using_address: "0.0.0.0:8900"
    heartbeat: 20
    allowed_hosts:
      - "2.2.2.2:8900"
  client1_to_relay:
    key: "32323232323232323232323232323232"
    send_using_address: "0.0.0.0:8900"
    heartbeat: 20
    allowed_hosts:
      - "relay.net:8900"
  client2_to_relay:
    key: "32323232323232323232323232323232"
    send_using_address: "0.0.0.0:8900"
    heartbeat: 20
    allowed_hosts:
      - "relay.net:8900"
  static_relay:
    key: "32323232323232323232323232323232"
    send_using_address: "0.0.0.0:8900"
    heartbeat: 20
    allowed_hosts:
      - "client1_ip:8900:latest" # latest - client source port from the latest received message
      - "client2_ip:8900:latest"
  dynamic_relay:
    key: "32323232323232323232323232323232"
    send_using_address: "0.0.0.0:8900"
    heartbeat: 20
    allowed_hosts:
      - "relay.net:8900"
    relay:
      host: "relay.net:8900" # relay clipboards through this server
      public_key: "some key"

  local_network_file:
    key: "32323232323232323232323232323232"
    clipboard: /tmp/cliboard # sync file
  local_network_dir:
    key: "32323232323232323232323232323232"
    clipboard: /tmp/clipboard/dir/ # sync dir
  receive_only_dir:
    key: "32323232323232323232323232323232"
    clipboard: /tmp/clipboard/dir/ # files will be created as /tmp/clipboard/dir/192.168.0.111
    allowed_hosts:
      - "192.168.0.111:0" # port 0 - receive only
      - "192.168.0.112:0"
    protocol: basic
  quic_full:
    clipboard: /tmp/clipboard/dir/ # files will be created as /tmp/clipboard/dir/192.168.0.111
    allowed_hosts:
      - "192.168.0.111:0" # port 0 - receive only
      - "192.168.0.112:0"
    protocol: quic
